[build]
  publish = "website"
  command = "# no build command needed"

[[redirects]]
  from = "/invite"
  to = "https://discord.com/oauth2/authorize?client_id=1304755116255088670"
  status = 302

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/9bPsjgnJ5v"
  status = 302

[[redirects]]
  from = "/github"
  to = "https://github.com/Drago-03/IndieGo.git"
  status = 302

[headers]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"